support tls
denodrivers/mysql pull request #154
Opened 2023-04-26 12:12 UTC by shiyuhang0

2023-04-27 03:57 UTC, shiyuhang0 commented
@lideming PTAL, this pr lacks tests but I think it is also ready for review. I will continue trying to add test for it

2023-07-08 16:04 UTC, lino-levan commented
@uki00a can you take a look?

2023-07-09 03:56 UTC, uki00a requested changes
@shiyuhang0 Nice work! I've left a few comments, but otherwise it looks good to me overall
@lideming Could you PTAL if you have time?

2023-07-09 03:56 UTC, uki00a commented on src/client.ts
> +
I think this enum shoud be re-exported from `mod.ts`

https://github.com/denodrivers/mysql/blob/6904845798ab63a28b9159488a62ffcf1db15b52/mod.ts#L2

2023-07-09 03:56 UTC, uki00a commented on src/client.ts
> +  mode?: string;
It would be good to use `TSLMode` or a union type to improve type safety:
```suggestion
  mode?: TLSMode;
```

2023-07-09 03:56 UTC, uki00a commented on src/packets/builders/auth.ts
> +  const clientParam: number = clientCapabilities(packet, {
nit: I think `params` could be passed directly to `clientCapabilities`:
```suggestion
  const clientParam: number = clientCapabilities(packet, params);
```

2023-07-09 10:18 UTC, lideming approved these changes

2023-08-17 05:17 UTC, shiyuhang0 commented
@uki00a Thank you for your review and I have optimized the code according to your comment. PTAL again.
This pr excludes the `mariadb:latest` in the GitHub action test to pass all checks. 

This test will fail with the following message:
```
OCI runtime exec failed: exec failed: unable to start container process: exec: "mysql": executable file not found in $PATH: unknown
```
But it is not the fault of this pr, it will fail even in master https://github.com/denodrivers/mysql/pull/160. I think we can skip this test in this pr and open another pr to fix it.

2023-08-19 14:07 UTC, uki00a approved these changes
LGTM. Nice work!

2023-08-22 06:24 UTC, shiyuhang0 commented
@lideming can this pr be merged?

2023-08-22 06:33 UTC, merged